import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { loadStripe } from '@stripe/stripe-js';
import { useEffect, useRef, useState } from 'react';

export default function Home() {
  const stripeRef = useRef<any>(null)
  useEffect(() => {
    const init = async () => {
      const stripe = await loadStripe('pk_test_adtMGXLLkiUBWa5xTpC2NRXJ', {
        stripeAccount: 'acct_1JjpDMQ9DTJCEgzc'
      });
      stripeRef.current = stripe
    }
    init()
  }, [])

  const [cardId, setCardId] = useState('ic_1K6CnFQ9DTJCEgzcrDT6UNgc')

  return (
    <div className={styles.container}>
      <Head>
        <title>Get card pin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input value={cardId} onChange={(e) => setCardId(e.currentTarget.value)} />
        <button onClick={async () => {
          const nonceResult = await stripeRef.current.createEphemeralKeyNonce({
            issuingCard: cardId,
          });
          const nonce = nonceResult.nonce;
          const ephemeralKeyResult = await fetch('/api/ephemeral-keys', {
            method: 'POST',
            body: JSON.stringify({ cardId, nonce }),
          });
          const ephemeralKeyResponse = await ephemeralKeyResult.json();
          const ephemeralKeySecret = ephemeralKeyResponse.ephemeralKeySecret;
          const pinElement = stripeRef.current.elements().create('issuingCardPinDisplay', {
            issuingCard: cardId,
            nonce,
            ephemeralKeySecret: ephemeralKeySecret,
          });
          pinElement.mount('#card-pin');
          pinElement.on('change', (event: any) => {
            console.log(event)
          })
        }}>Get</button>
        <div id="card-pin"></div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
